// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SupremeBot.Data;

namespace SupremeBot.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20200107194949_Mig1")]
    partial class Mig1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SupremeBot.Models.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address1");

                    b.Property<string>("City");

                    b.Property<string>("Email");

                    b.Property<string>("FullName");

                    b.Property<string>("Name");

                    b.Property<string>("PhoneNumber");

                    b.Property<string>("PostCode");

                    b.HasKey("Id");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("SupremeBot.Models.Card", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CVV");

                    b.Property<string>("Month");

                    b.Property<string>("Name");

                    b.Property<string>("Number");

                    b.Property<int>("Type");

                    b.Property<string>("Year");

                    b.HasKey("Id");

                    b.ToTable("Cards");
                });

            modelBuilder.Entity("SupremeBot.Models.Color", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ItemId");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.ToTable("Colors");
                });

            modelBuilder.Entity("SupremeBot.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("AnyColor");

                    b.Property<int>("Category");

                    b.Property<int>("Size");

                    b.Property<int?>("TaskItemId");

                    b.HasKey("Id");

                    b.HasIndex("TaskItemId");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("SupremeBot.Models.ItemName", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ItemId");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.ToTable("ItemNames");
                });

            modelBuilder.Entity("SupremeBot.Models.TaskItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AddressId");

                    b.Property<bool>("AnyColor");

                    b.Property<int?>("CardId");

                    b.Property<int>("Delay");

                    b.Property<bool>("FillAdress");

                    b.Property<int>("Hour");

                    b.Property<int>("Minute");

                    b.Property<bool>("OnlyWithEmptyBasket");

                    b.Property<int>("RefreshInterval");

                    b.Property<int>("Second");

                    b.Property<bool>("UseTimer");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.HasIndex("CardId");

                    b.ToTable("TaskItems");
                });

            modelBuilder.Entity("SupremeBot.Models.Color", b =>
                {
                    b.HasOne("SupremeBot.Models.Item")
                        .WithMany("Colors")
                        .HasForeignKey("ItemId");
                });

            modelBuilder.Entity("SupremeBot.Models.Item", b =>
                {
                    b.HasOne("SupremeBot.Models.TaskItem")
                        .WithMany("Items")
                        .HasForeignKey("TaskItemId");
                });

            modelBuilder.Entity("SupremeBot.Models.ItemName", b =>
                {
                    b.HasOne("SupremeBot.Models.Item")
                        .WithMany("Names")
                        .HasForeignKey("ItemId");
                });

            modelBuilder.Entity("SupremeBot.Models.TaskItem", b =>
                {
                    b.HasOne("SupremeBot.Models.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId");

                    b.HasOne("SupremeBot.Models.Card", "Card")
                        .WithMany()
                        .HasForeignKey("CardId");
                });
#pragma warning restore 612, 618
        }
    }
}
